<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Snooze plugin             |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-snooze/
*/

$labels = [];
$labels['buttontext'] = 'Snooze';
$labels['buttontitle'] = 'Snooze this message';
$labels['snoozedSuccess'] = 'Successfully snoozed';
$labels['snoozeError'] = 'Some messages could not be snoozed';
$labels['snoozefolder'] = 'Snoozed';
$labels['unsnooze'] = 'Unsnooze';
$labels['snoozingmessages'] = 'Snoozing message(s)...';
$labels['timesOfDay'] = 'Times of Day';
$labels['morningTime'] = 'Morning time:';
$labels['eveningTime'] = 'Evening time:';
$labels['snoozeUntil'] = 'Snooze until...';
$labels['snoozedUntil'] = 'Snoozed until ';
$labels['snoozed'] = 'Snoozed ';
$labels['snoozeSettings'] = 'Snooze';

$labels['latertoday'] = "Later today";
$labels['tomorrow'] = "Tomorrow";
$labels['laterthisweek'] = "Later this week";
$labels['thisweekend'] = "This Weekend";
$labels['nextweekend'] = "Next Weekend";
$labels['nextweek'] = "Next Week";
$labels['pickatime'] = "Pick date & time";
$labels['snoozeButton'] = "Snooze";
$labels['dateLabel'] = "Date:";
$labels['timeLabel'] = "Time:";
$labels['invalidDate'] = "Please choose a date in the future.";

